services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ApiKit\Response\ResponseFactory:
        public: true
        arguments:
            $responseConfig: '%api_kit.response%'

    ApiKit\Response\ResponseFactoryInterface:
        alias: ApiKit\Response\ResponseFactory
        public: true

    ApiKit\EventListener\ExceptionListener:
        arguments:
            $exceptionConfig: '%api_kit.exception_handling%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
